/*
 * UddiP2PTesterGUI.java
 *
 * Created on August 26, 2002, 2:56 PM
 */

package psl.discus.javasrc.uddi;

import javax.swing.*;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.io.*;
import java.awt.*;

/**
 *
 * @author  Matias
 */
public class UddiP2PTesterGUI extends javax.swing.JFrame {

    private UddiP2PTester tester;

    /** Creates new form UddiP2PTesterGUI */
    public UddiP2PTesterGUI() {
        initComponents();
        System.setOut(new TextAreaPrintStream());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        jScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);

        logText = new javax.swing.JTextArea();
        logText.setFont(new Font("Courier new", Font.PLAIN, 12));
        logText.setAutoscrolls(true);

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serviceNameText = new javax.swing.JTextField();
        sendFindServices = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        sendGetServiceDetails = new javax.swing.JButton();

        setTitle("UddiP2PTester");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.setPreferredSize(new Dimension(500,300));

        jScrollPane.setViewportView(logText);

        jPanel1.add(jScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(100, 75));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Service Name:");
        jPanel2.add(jLabel1);

        serviceNameText.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel2.add(serviceNameText);

        sendFindServices.setText("Send query");
        sendFindServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFindServicesActionPerformed(evt);
            }
        });

        jPanel2.add(sendFindServices);

        jTabbedPane2.addTab("FindService", jPanel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        sendGetServiceDetails.setText("Send query");
        sendGetServiceDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendGetServiceDetailsActionPerformed(evt);
            }
        });

        jPanel4.add(sendGetServiceDetails);

        jTabbedPane2.addTab("GetServiceDetails", jPanel4);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void sendGetServiceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendGetServiceDetailsActionPerformed

        (new SendQueryThread(SendQueryThread.GETDETAILS_QUERY)).start();

    }//GEN-LAST:event_sendGetServiceDetailsActionPerformed

    private void sendFindServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFindServicesActionPerformed

        (new SendQueryThread(SendQueryThread.FIND_QUERY)).start();

    }//GEN-LAST:event_sendFindServicesActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new UddiP2PTesterGUI().show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea logText;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField serviceNameText;
    private javax.swing.JButton sendFindServices;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton sendGetServiceDetails;
    // End of variables declaration//GEN-END:variables

    final class TextAreaPrintStream extends PrintStream {

        JTextArea textArea = logText;

        public TextAreaPrintStream() {
            super(System.out);
            this.textArea = textArea;
        }

        public void println(String x) {
            //super.println(x);
            textArea.append(x);
            textArea.repaint();
        }

        public void print(String s) {
            //super.print(s);
            textArea.append(s);
            textArea.repaint();
        }


        public void write(byte buf[], int off, int len) {
            //super.write(buf, off, len);
            textArea.append(new String(buf,off,len));
            textArea.repaint();
        }


    }

    /**
     * Used to send queries asynchronously
     */
    private final class SendQueryThread extends Thread {

        private static final int FIND_QUERY=1, GETDETAILS_QUERY=2;
        private int queryType;

        public SendQueryThread(int queryType) {
            this.queryType = queryType;
        }

        public void run() {
            if (tester == null)
                tester = new UddiP2PTester();

            if (queryType == FIND_QUERY) {
                tester.sendFindServiceQuery(serviceNameText.getText());
            } else if (queryType == GETDETAILS_QUERY) {
                tester.sendGetServiceDetailsQuery();
            }

        }

    }

}
