/*
 * UddiP2PTesterGUI.java
 *
 * Created on August 26, 2002, 2:56 PM
 */

package psl.discus.javasrc.uddi;

import psl.discus.javasrc.security.ServiceSpace;
import psl.discus.javasrc.p2p.ServiceSpaceEndpoint;

import javax.swing.*;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.io.*;
import java.awt.*;

/**
 * A GUI for the UddiP2PTester class
 * @author  Matias
 */
public class UddiP2PTesterGUI extends javax.swing.JFrame {

    private UddiP2PTester tester;

    public UddiP2PTesterGUI(UddiP2PTester tester) {
        initComponents();
        serviceSpaceList.setModel(new DefaultListModel());

        System.setOut(new TextAreaPrintStream());
        this.tester = tester;
    }

    /**
     * Set the service space list to the given array of service spaces
     */
    public void setServiceSpaces(Object[] serviceSpaces) {
        serviceSpaceList.setListData(serviceSpaces);
    }

    /**
     * Add the given service space to the list of available service spaces
     */
    public void addServiceSpace(Object serviceSpace) {
        ((DefaultListModel) serviceSpaceList.getModel()).addElement(serviceSpace);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        queryType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serviceSpaceList = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        findServiceRadio = new javax.swing.JRadioButton();
        findServiceText = new javax.swing.JTextField();
        getDetailsRadio = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();


        setTitle("UddiP2PTester");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(85, 123));
        logText.setPreferredSize(new java.awt.Dimension(100, 120));
        jScrollPane1.setViewportView(logText);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(301, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        jLabel2.setText("Service Space Endpoints:");
        jPanel4.add(jLabel2);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 60));
        serviceSpaceList.setPreferredSize(new java.awt.Dimension(10, 10));
        jScrollPane2.setViewportView(serviceSpaceList);

        jPanel4.add(jScrollPane2);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        findServiceRadio.setText("FindService");
        queryType.add(findServiceRadio);
        jPanel5.add(findServiceRadio);

        jPanel5.add(findServiceText);

        getDetailsRadio.setText("GetDetails");
        queryType.add(getDetailsRadio);
        jPanel5.add(getDetailsRadio);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jButton1.setText("Send query");
        jPanel6.add(jButton1);

        jPanel3.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void sendGetServiceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendGetServiceDetailsActionPerformed

        (new SendQueryThread(SendQueryThread.GETDETAILS_QUERY)).start();

    }//GEN-LAST:event_sendGetServiceDetailsActionPerformed

    private void sendFindServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFindServicesActionPerformed

        (new SendQueryThread(SendQueryThread.FIND_QUERY)).start();

    }//GEN-LAST:event_sendFindServicesActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup queryType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList serviceSpaceList;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton findServiceRadio;
    private javax.swing.JTextField findServiceText;
    private javax.swing.JRadioButton getDetailsRadio;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    // this class is used to redirect the log output to the TextArea box
    final class TextAreaPrintStream extends PrintStream {

        JTextArea textArea = logText;

        public TextAreaPrintStream() {
            super(System.out);
            this.textArea = textArea;
        }

        public void println(String x) {
            //super.println(x);
            textArea.append(x);
            textArea.repaint();
        }

        public void print(String s) {
            //super.print(s);
            textArea.append(s);
            textArea.repaint();
        }


        public void write(byte buf[], int off, int len) {
            //super.write(buf, off, len);
            textArea.append(new String(buf,off,len));
            textArea.repaint();
        }


    }

    /**
     * Used to send queries asynchronously
     */
    private final class SendQueryThread extends Thread {

        private static final int FIND_QUERY=1, GETDETAILS_QUERY=2;
        private int queryType;

        public SendQueryThread(int queryType) {
            this.queryType = queryType;
        }

        public void run() {
           if (queryType == FIND_QUERY) {
                tester.sendFindServiceQuery(findServiceText.getText());
            } else if (queryType == GETDETAILS_QUERY) {
                ServiceSpaceEndpoint endpoint = (ServiceSpaceEndpoint) serviceSpaceList.getSelectedValue();
                tester.sendGetServiceDetailsQuery(endpoint);
            }

        }

    }

}
